---
language: python
services: docker

install:
  # Install Ansible.
  - pip install ansible docker-py

  # Install role dependencies.
  - ansible-galaxy install -r requirements.yml

script:
  # Build the container.
  - ansible-playbook main.yml

  # Verify the container runs and returns the default welcome page.
  - docker run -d --name=php -p 8080:80 php-apache:latest /usr/sbin/apache2ctl -D FOREGROUND
  - docker ps
  - curl http://localhost:8080/

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
