---
language: python
services: docker

env:
  - php_version: '7.2'
  - php_version: '7.1'
  - php_version: '7.0'
  - php_version: '5.6'

install:
  # Install Ansible.
  - pip install ansible docker
  - export ANSIBLE_FORCE_COLOR=true

  # Install role dependencies.
  - ansible-galaxy install -r requirements.yml

script:
  # Build the container.
  - ansible-playbook --extra-vars="@vars/${php_version}.yml" main.yml

  # Verify the container runs and has the correct PHP version.
  - docker run -d --name=php-apache -p 8080:80 geerlingguy/php-apache:${php_version} /usr/sbin/apache2ctl -D FOREGROUND
  - docker exec php-apache php -v | grep ${php_version}
  - curl http://localhost:8080/

after_success:
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      # Log into Docker Hub.
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Push $php_version tag.
      docker push geerlingguy/php-apache:${php_version}

      # Push $php_version + '.x' tag.
      docker tag geerlingguy/php-apache:${php_version} geerlingguy/php-apache:${php_version}.x
      docker push geerlingguy/php-apache:${php_version}.x

      # Push latest tag if building latest version.
      if [[ "$php_version" == "7.2" ]]; then
        docker tag geerlingguy/php-apache:${php_version} geerlingguy/php-apache:latest
        docker push geerlingguy/php-apache:latest
      fi
    fi
